"""Time-series anomaly-detection methods.

Install the project environment before importing this package::

    uv sync
"""

from .AERCA import AERCA, AERCAConfig, AERCALightningModule, AERCALoss, AERCAOutput
from .AxonAD import AxonAD, AxonADConfig, AxonADLightningModule, AxonADLoss, AxonADOutput
from .baseline import (
    BASELINES,
    ClusterLocalOutlierFactorConfig,
    ConnectivityOutlierFactorConfig,
    CopulaConfig,
    ExtendedIsolationForestConfig,
    FourierConfig,
    HistogramConfig,
    IsolationForestConfig,
    KMeansDistanceConfig,
    LocalOutlierFactorConfig,
    LocalPolynomialConfig,
    MatrixProfileConfig,
    MinimumCovarianceDeterminantConfig,
    NearestNeighborsConfig,
    OneClassSVMConfig,
    PrincipalComponentConfig,
    RobustPCAConfig,
    SpectralResidualConfig,
    StatisticalFeaturesConfig,
    StreamingMatrixProfileConfig,
    cluster_local_outlier_factor_score,
    connectivity_outlier_factor_score,
    copula_score,
    extended_isolation_forest_score,
    fourier_score,
    histogram_score,
    isolation_forest_score,
    kmeans_distance_score,
    local_outlier_factor_score,
    local_polynomial_score,
    matrix_profile_score,
    minimum_covariance_determinant_score,
    nearest_neighbors_score,
    one_class_svm_score,
    principal_component_score,
    robust_pca_score,
    spectral_residual_score,
    statistical_features_score,
    streaming_matrix_profile_score,
)
from .CARLA import (
    CARLA,
    CARLAClassificationLightningModule,
    CARLAConfig,
    CARLALoss,
    CARLAOutput,
    CARLAPretextLightningModule,
    inject_anomalies,
)
from .CrossAD import CrossAD, CrossADConfig, CrossADLightningModule, CrossADLoss, CrossADOutput
from .DADA import DADA, DADAConfig, DADALightningModule, DADAOutput
from .KanAD import KANAD, KANADConfig, KANADLightningModule, KANADLoss, KANADOutput
from .Left import Left, LeftConfig, LeftLightningModule, LeftLoss, LeftOutput
from .MMPAD import MMPADConfig, MMPADReference, build_reference, score as mmpad_score
from .PaAno import PaAno, PaAnoConfig, PaAnoLightningModule, PaAnoLoss, PatchEncoder
from .ScatterAD import (
    ScatterAD,
    ScatterADConfig,
    ScatterADLightningModule,
    ScatterADLoss,
    ScatterADOutput,
)
from .TimeRCD import TimeRCD, TimeRCDConfig, TimeRCDLightningModule, TimeRCDLoss, TimeRCDOutput
from .TSPulse import (
    TSPulse,
    TSPulseConfig,
    TSPulseFineTune,
    TSPulseLightningModule,
    TSPulseLoss,
    TSPulseOutput,
    TSPulseZeroShot,
)
from .XLSTMAD import XLSTMAD, XLSTMADConfig, XLSTMADLightningModule, XLSTMADLoss, XLSTMADOutput

METHODS = {
    "AERCA": AERCA,
    "AxonAD": AxonAD,
    "CARLA": CARLA,
    "CrossAD": CrossAD,
    "DADA": DADA,
    "KAN-AD": KANAD,
    "Left": Left,
    "PaAno": PaAno,
    "ScatterAD": ScatterAD,
    "Time-RCD": TimeRCD,
    "TSPulse-FT": TSPulseFineTune,
    "TSPulse-ZS": TSPulseZeroShot,
    "xLSTMAD": XLSTMAD,
}

__all__ = [
    "METHODS",
    "BASELINES",
    "AERCA",
    "AERCAConfig",
    "AERCALightningModule",
    "AERCALoss",
    "AERCAOutput",
    "AxonAD",
    "AxonADConfig",
    "AxonADLightningModule",
    "AxonADLoss",
    "AxonADOutput",
    "CARLA",
    "CARLAConfig",
    "CARLAClassificationLightningModule",
    "CARLALoss",
    "CARLAOutput",
    "CARLAPretextLightningModule",
    "ClusterLocalOutlierFactorConfig",
    "ConnectivityOutlierFactorConfig",
    "CopulaConfig",
    "CrossAD",
    "CrossADConfig",
    "CrossADLightningModule",
    "CrossADLoss",
    "CrossADOutput",
    "DADA",
    "DADAConfig",
    "DADALightningModule",
    "DADAOutput",
    "ExtendedIsolationForestConfig",
    "FourierConfig",
    "HistogramConfig",
    "IsolationForestConfig",
    "KANAD",
    "KANADConfig",
    "KANADLightningModule",
    "KANADLoss",
    "KANADOutput",
    "KMeansDistanceConfig",
    "Left",
    "LeftConfig",
    "LeftLightningModule",
    "LeftLoss",
    "LeftOutput",
    "LocalOutlierFactorConfig",
    "LocalPolynomialConfig",
    "MMPADConfig",
    "MMPADReference",
    "MatrixProfileConfig",
    "MinimumCovarianceDeterminantConfig",
    "NearestNeighborsConfig",
    "OneClassSVMConfig",
    "PaAno",
    "PaAnoConfig",
    "PrincipalComponentConfig",
    "PaAnoLightningModule",
    "PaAnoLoss",
    "PatchEncoder",
    "RobustPCAConfig",
    "SpectralResidualConfig",
    "StatisticalFeaturesConfig",
    "StreamingMatrixProfileConfig",
    "ScatterAD",
    "ScatterADConfig",
    "ScatterADLightningModule",
    "ScatterADLoss",
    "ScatterADOutput",
    "TimeRCD",
    "TimeRCDConfig",
    "TimeRCDLightningModule",
    "TimeRCDLoss",
    "TimeRCDOutput",
    "TSPulse",
    "TSPulseConfig",
    "TSPulseFineTune",
    "TSPulseLightningModule",
    "TSPulseLoss",
    "TSPulseOutput",
    "TSPulseZeroShot",
    "XLSTMAD",
    "XLSTMADConfig",
    "XLSTMADLightningModule",
    "XLSTMADLoss",
    "XLSTMADOutput",
    "build_reference",
    "cluster_local_outlier_factor_score",
    "connectivity_outlier_factor_score",
    "copula_score",
    "extended_isolation_forest_score",
    "fourier_score",
    "histogram_score",
    "inject_anomalies",
    "isolation_forest_score",
    "kmeans_distance_score",
    "local_outlier_factor_score",
    "local_polynomial_score",
    "matrix_profile_score",
    "minimum_covariance_determinant_score",
    "mmpad_score",
    "nearest_neighbors_score",
    "one_class_svm_score",
    "principal_component_score",
    "robust_pca_score",
    "spectral_residual_score",
    "statistical_features_score",
    "streaming_matrix_profile_score",
]
